-- ============================================================
-- SCALABLE CRM SCHEMA EXTENSIONS
-- ------------------------------------------------------------
-- PURPOSE (NON-TECH EXPLANATION)
--
-- This file defines NEW tables and NEW columns that sit on top
-- of our existing database. It is designed so the system can
-- scale to:
-- - CRE workspace
-- - Receptionist walk-in flow
-- - RM / TL / GM workspaces
-- - Future roles (Finance, etc.)
--
-- The main idea is:
-- - "CUSTOMER" = the person (phone & identity)
-- - "LEAD"      = one sales opportunity for that person
--                 in a specific branch / team / time
--
-- Why do we need a separate "customers" table when we already
-- have "leads_master"?
--
-- - Today, every time a lead is created, the name + phone are
--   stored inside "leads_master".
-- - When the same person comes again (same phone) or visits a
--   different branch, they become another row in "leads_master".
-- - Business questions like:
--     "How many times did this customer visit us?"
--     "Which branches handled this same person?"
--   are very hard to answer, because we don't have ONE place
--   which represents the person.
--
-- So we introduce "customers" as a single, clean record per
-- person (mostly keyed by phone number). Leads still keep their
-- own copy of name / remarks for compatibility, but the true
-- identity lives in "customers".
--
-- This is NOT "keeping the same data in two places" just for
-- fun:
-- - "customers.full_name" = who the person is overall
-- - "leads_master.full_name" = what name was used for THIS
--   lead / this visit (it might be slightly different spelling
--   or updated later). This helps us keep history without
--   breaking old data.
--
-- Managers can think about it like:
-- - "Customer card" (customers table) shows the entire story of
--   the person.
-- - "Lead file" (leads_master row) is one folder inside one
--   branch about that person for one journey.
--
-- IMPORTANT:
-- - This file is a proposal for schema changes.
-- - Apply carefully in Supabase after review.
-- ============================================================


-- ============================================================
-- ============================================================

CREATE TABLE IF NOT EXISTS public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Phone number is our main way to recognise a person.
  phone_number_normalized TEXT NOT NULL UNIQUE,
  -- Basic details that belong to the person, not to a single lead.
  full_name TEXT,
  email TEXT,
  city TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);


-- ============================================================
-- 2. LINK LEADS TO CUSTOMERS AND BRANCHES
--    (ONE LEAD PER CUSTOMER PER BRANCH)
-- ============================================================

ALTER TABLE public.leads_master
  ADD COLUMN IF NOT EXISTS customer_id BIGINT,
  ADD COLUMN IF NOT EXISTS branch_id BIGINT;

ALTER TABLE public.leads_master
  ADD CONSTRAINT leads_master_customer_id_fkey
    FOREIGN KEY (customer_id) REFERENCES public.customers(id);

ALTER TABLE public.leads_master
  ADD CONSTRAINT leads_master_branch_id_fkey
    FOREIGN KEY (branch_id) REFERENCES public.branches(id);

-- Index to quickly find all leads for a customer in a branch,
-- and to help enforce the rule "only one open lead per customer
-- per branch" at the application level.
CREATE INDEX IF NOT EXISTS idx_leads_master_customer_branch_status
  ON public.leads_master (customer_id, branch_id, status);


-- ============================================================
-- 3. RM QUALIFICATION FIELDS
--    (EXTRA DETAILS FILLED BY RM AFTER CRE/RECEPTIONIST)
-- ============================================================

ALTER TABLE public.leads_qualification
  ADD COLUMN IF NOT EXISTS age_group TEXT,
  ADD COLUMN IF NOT EXISTS gender TEXT,
  ADD COLUMN IF NOT EXISTS income_group TEXT,
  ADD COLUMN IF NOT EXISTS buying_for TEXT,              -- 'Self' / 'Family'
  ADD COLUMN IF NOT EXISTS daily_running_km INTEGER,
  ADD COLUMN IF NOT EXISTS current_car_details TEXT,      -- Free-text description
  ADD COLUMN IF NOT EXISTS buyer_type TEXT,               -- First-time / Additional / Replacement
  ADD COLUMN IF NOT EXISTS evaluation_required BOOLEAN,
  ADD COLUMN IF NOT EXISTS old_car_details TEXT,
  ADD COLUMN IF NOT EXISTS old_car_expected_price NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS existing_mg_customer BOOLEAN,
  ADD COLUMN IF NOT EXISTS family_members_count INTEGER;

-- Note:
-- - Table already has flags: TEST_DRIVE, BOOKED, RETAILED
-- - It also already has branch_id, tl_id, rm_id
--   which we will use for RM / TL analytics.


-- ============================================================
-- 4. TEST DRIVES (MULTIPLE PER LEAD)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.test_drives (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES public.leads_master(id),
  customer_id BIGINT REFERENCES public.customers(id),
  branch_id BIGINT REFERENCES public.branches(id),
  model TEXT,
  variant TEXT,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  given_by_user_id BIGINT REFERENCES public.users(user_id),
  created_by_user_id BIGINT REFERENCES public.users(user_id),
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_test_drives_lead_id
  ON public.test_drives(lead_id);


-- ============================================================
-- 5. BOOKINGS (RM FILLS, GM APPROVES)
--    THIS SUPPORTS:
--    - BOOKING DOCKET
--    - GM APPROVAL WORKFLOW
--    - FUTURE FINANCE MODULE
-- ============================================================

CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Link to the lead and qualification it belongs to
  lead_id BIGINT NOT NULL REFERENCES public.leads_master(id),
  qualification_id BIGINT REFERENCES public.leads_qualification(id),
  branch_id BIGINT REFERENCES public.branches(id),
  rm_member_id BIGINT REFERENCES public.branch_members(id), -- RM who booked

  -- Commercial details filled by RM
  vehicle_price NUMERIC(14,2),
  discounts_offered NUMERIC(14,2),
  special_commitments TEXT,
  booking_amount NUMERIC(14,2),
  payment_mode TEXT,                        -- Cash / Card / UPI / Finance / etc.
  transaction_details TEXT,
  transaction_proof_url TEXT,               -- Image path or storage URL
  expected_delivery_date DATE,
  mode_of_purchase TEXT,                    -- Outright / Finance / Lease, etc.

  -- Approval workflow
  status TEXT NOT NULL DEFAULT 'pending_approval',
  -- e.g. 'pending_approval' | 'approved' | 'rejected' | 'cancelled'

  gm_approved_by BIGINT REFERENCES public.users(user_id),
  gm_approved_at TIMESTAMPTZ,
  gm_remarks TEXT,

  created_by_user_id BIGINT REFERENCES public.users(user_id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bookings_lead_id
  ON public.bookings(lead_id);

CREATE INDEX IF NOT EXISTS idx_bookings_status
  ON public.bookings(status);


-- ============================================================
-- 6. RETAIL STAGE (FINAL DELIVERY / INVOICING)
--    SEPARATE TABLE SO FINANCE / ACCOUNTS CAN EXTEND IT
--    WITHOUT TOUCHING LEAD OR BOOKING STRUCTURE.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.retails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  booking_id BIGINT NOT NULL REFERENCES public.bookings(id),
  lead_id BIGINT NOT NULL REFERENCES public.leads_master(id),

  status TEXT NOT NULL DEFAULT 'pending_approval',
  -- 'pending_approval' | 'approved' | 'rejected'

  invoice_number TEXT,
  invoice_date DATE,
  on_road_price NUMERIC(14,2),
  remarks TEXT,

  gm_approved_by BIGINT REFERENCES public.users(user_id),
  gm_approved_at TIMESTAMPTZ,
  gm_remarks TEXT,

  created_by_user_id BIGINT REFERENCES public.users(user_id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_retails_lead_id
  ON public.retails(lead_id);

CREATE INDEX IF NOT EXISTS idx_retails_status
  ON public.retails(status);


-- ============================================================
-- 7. NOTIFICATIONS / REMINDERS (IN-APP)
--    USED FOR:
--    - GM → RM / TL reminders
--    - System → "booking waiting for approval", "follow-up due"
-- ============================================================

CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(user_id),

  type TEXT NOT NULL,             -- 'booking_approval', 'retail_approval', 'followup_due', etc.
  title TEXT,
  message TEXT,

  related_lead_id BIGINT REFERENCES public.leads_master(id),
  related_booking_id BIGINT REFERENCES public.bookings(id),
  related_retail_id BIGINT REFERENCES public.retails(id),

  status TEXT NOT NULL DEFAULT 'unread',  -- 'unread' | 'read'
  created_at TIMESTAMPTZ DEFAULT now(),
  read_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_status
  ON public.notifications(user_id, status);


-- ============================================================
-- 8. OPTIONAL: EXTEND BRANCH MEMBERS FOR RECEPTIONIST ROLE
--    (ONLY IF YOU WANT TO MAP RECEPTIONISTS TO BRANCHES HERE)
-- ============================================================

-- NOTE: Your existing CHECK constraint on branch_members.role
-- currently allows only: 'TL', 'RM', 'CRE'.
-- If you want to track Receptionists per branch in this table,
-- you can update the constraint like this (run manually if needed):
--
-- ALTER TABLE public.branch_members
--   DROP CONSTRAINT IF EXISTS branch_members_role_check;
--
-- ALTER TABLE public.branch_members
--   ADD CONSTRAINT branch_members_role_check
--   CHECK (role = ANY (ARRAY['TL','RM','CRE','Receptionist']));
--
-- If you prefer to keep Receptionists only in users.role for now,
-- you can skip this step.


-- ============================================================
-- 9. ADMIN-MANAGED MASTER DATA (MODELS, VARIANTS, LOCATIONS,
--    PENDING REASONS, UNQUALIFIED REASONS)
-- ============================================================

-- 9.1 VEHICLE MODELS
CREATE TABLE IF NOT EXISTS public.vehicle_models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INTEGER,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 9.2 VEHICLE VARIANTS (PER MODEL)
CREATE TABLE IF NOT EXISTS public.vehicle_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id BIGINT NOT NULL REFERENCES public.vehicle_models(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INTEGER,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT vehicle_variants_unique_name_per_model UNIQUE (model_id, name)
);

CREATE INDEX IF NOT EXISTS idx_vehicle_variants_model_id
  ON public.vehicle_variants(model_id);


-- 9.3 LOCATIONS (FOR CUSTOMER LOCATION / SHOWROOM AREAS)
CREATE TABLE IF NOT EXISTS public.locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT,
  branch_id BIGINT REFERENCES public.branches(id),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INTEGER,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT locations_unique_name_per_branch UNIQUE (branch_id, name)
);

CREATE INDEX IF NOT EXISTS idx_locations_branch_id
  ON public.locations(branch_id);


-- 9.4 PENDING REASONS (WHY LEAD IS STILL PENDING)
CREATE TABLE IF NOT EXISTS public.pending_reasons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,         -- short key, e.g. 'CALL_LATER', 'WAITING_FUNDS'
  label TEXT NOT NULL,               -- human readable, e.g. 'Customer asked to call later'
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  applies_to_stage TEXT,             -- e.g. 'RM', 'CRE', 'Receptionist' (optional)
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);


-- 9.5 UNQUALIFIED / LOST REASONS
CREATE TABLE IF NOT EXISTS public.unqualified_reasons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,         -- e.g. 'PRICE', 'COMPETITOR', 'NO_REQUIREMENT'
  label TEXT NOT NULL,               -- e.g. 'Price too high', 'Bought competitor car'
  description TEXT,
  category TEXT,                     -- optional grouping, e.g. 'Commercial', 'Product', 'Service'
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  applies_to_stage TEXT,             -- e.g. 'RM', 'CRE', 'Receptionist' (optional)
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);


-- ============================================================
-- END OF SCALABLE CRM SCHEMA EXTENSIONS
-- ============================================================


